name: Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  deploy-contracts:
    name: deploy-contracts
    runs-on: ubuntu-latest
    environment: amoy
    steps:
      - uses: actions/checkout@v4
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
      - name: Deploy contracts to Polygon Amoy
        working-directory: contracts
        env:
          AMOY_RPC_URL: ${{ secrets.AMOY_RPC_URL }}
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          PROTOCOL_TREASURY: ${{ secrets.PROTOCOL_TREASURY }}
          POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}
        run: forge script script/Deploy.s.sol --rpc-url $AMOY_RPC_URL --broadcast --verify
